export { default as Main } from "./Main";
export { default as Header } from "./Header";
export { default as Slider } from "./Slider";
export { default as Vector } from "./Vector";
export { default as Taina } from "./Taina";
export { default as Vika } from "./Vika";
export { default as Leader } from "./Leader";
export { default as Dmd } from "./Dmd";
export { default as Footer } from "./Footer";
